base_url = "https://nullis.xyz"
compile_sass = true
build_search_index = true
generate_feeds = true
title = "Nullis"
description = "Nullis development studio - Building robust, scalable solutions with a focus on security and efficiency"

taxonomies = [
    {name = "categories", feed = true, paginate_by = 10},
    {name = "tags", feed = true, paginate_by = 10}
]

[markdown]
highlight_code = true
highlight_theme = "css"
highlight_themes_css = [
    { theme = "solarized-dark", filename = "solarized-dark.css" },
    { theme = "solarized-light", filename = "solarized-light.css" }
]
external_links_target_blank = true
external_links_no_follow = true
external_links_no_referrer = true

[extra]
pagination_path = "page"
address = ["123 Main St", "Anytown, USA"]

# Site-wide Features
[extra.features]
dark_mode = true
search = false
comments = false
table_of_contents = true
related_pages = true
cta = true
grid_layout = true
stats = true

# Theme Configuration
theme_color = "#2b95b8"
site_pattern = "grid" # options: grid, dots

# Header Configuration
logo = "/images/logo.svg"
logo_dark = "/images/logo-dark.svg"

# Navigation Menu
[[extra.menu]]
label = "About"
url = "/about"

[[extra.menu]]
label = "Blog"
url = "/blog"

[[extra.menu]]
label = "Projects"
url = "/projects"
style = "primary" # This will make it stand out

[[extra.menu]]
label = "Contact"
url = "/contact"

[[extra.menu]]
label = "Manifesto"
url = "/manifesto"

# Author Information
[extra.author]
name = "John Citizen"
title = "Software Engineer & Systems Architect"
bio = "Software engineer focused on systems programming and distributed architecture. Building robust, scalable solutions with a focus on security and efficiency."
email = "john.doe@example.com"
twitter = "johndoe"
github = "johndoe"
linkedin = "johndoe"
avatar = "/images/avatar.jpg"

# Hero Section
[extra.hero]
title = "Building the Future of Distributed Systems"
subtitle = "Software Engineer & Systems Architect"
description = "Specializing in high-performance distributed systems, security infrastructure, and scalable architecture design."
gradient_title = true
pattern_background = true

[[extra.hero.actions]]
label = "View Projects"
url = "/projects"
style = "primary"
icon = """<svg viewBox="0 0 24 24" fill="none" stroke="currentColor"><path d="M10 20l4-16m4 4l4 4-4 4M6 16l-4-4 4-4"/></svg>"""

[[extra.hero.actions]]
label = "Read Blog"
url = "/blog"
style = "ghost"
icon = """<svg viewBox="0 0 24 24" fill="none" stroke="currentColor"><path d="M19 20H5a2 2 0 01-2-2V6a2 2 0 012-2h10a2 2 0 012 2v1m2 13a2 2 0 01-2-2V7m2 13a2 2 0 002-2V9.5a2.5 2.5 0 00-2.5-2.5H14"/></svg>"""

# Statistics
[extra.stats]
years_experience = "10+"
projects_completed = "50+"
happy_clients = "30+"
open_source = "15+"

# Featured Projects
[[extra.projects]]
title = "Distributed System Framework"
description = "High-performance distributed computing framework designed for scalability and fault tolerance."
image = "https://fakeimg.pl/640x480"
category = "Backend Development"
tags = ["Rust", "WebAssembly", "Kubernetes"]
github = "https://github.com/username/distributed-framework"
url = "https://framework.example.com"
featured = true

[[extra.projects]]
title = "Security Infrastructure Platform"
description = "Enterprise-grade security infrastructure platform with advanced threat detection."
image = "https://fakeimg.pl/640x480"
category = "Security"
tags = ["Go", "Terraform", "AWS"]
github = "https://github.com/username/security-platform"
url = "https://security.example.com"
featured = true

# Skills Categories
[[extra.skills]]
name = "Systems Programming"
icon = """<svg viewBox="0 0 24 24" fill="none" stroke="currentColor"><path d="M9 3v2m6-2v2M9 19v2m6-2v2M5 9H3m2 6H3m18-6h-2m2 6h-2M7 19h10a2 2 0 002-2V7a2 2 0 00-2-2H7a2 2 0 00-2 2v10a2 2 0 002 2zM9 9h6v6H9V9z"/></svg>"""
description = "Building high-performance, low-level software systems"
items = [
    { name = "Rust", level = "Expert" },
    { name = "C++", level = "Advanced" },
    { name = "Systems Architecture", level = "Expert" }
]

[[extra.skills]]
name = "Distributed Systems"
icon = """<svg viewBox="0 0 24 24" fill="none" stroke="currentColor"><path d="M5 12h14M5 12a2 2 0 01-2-2V6a2 2 0 012-2h14a2 2 0 012 2v4a2 2 0 01-2 2M5 12a2 2 0 00-2 2v4a2 2 0 002 2h14a2 2 0 002-2v-4a2 2 0 00-2-2m-2-4h.01M17 16h.01"/></svg>"""
description = "Designing and implementing scalable distributed systems"
items = [
    { name = "Kubernetes", level = "Expert" },
    { name = "Docker", level = "Expert" },
    { name = "Microservices", level = "Advanced" }
]


# Social Links Configuration
[[extra.social_links]]
name = "GitHub"
url = "https://github.com/nullis"
icon = """<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M9 19c-5 1.5-5-2.5-7-3m14 6v-3.87a3.37 3.37 0 0 0-.94-2.61c3.14-.35 6.44-1.54 6.44-7A5.44 5.44 0 0 0 20 4.77 5.07 5.07 0 0 0 19.91 1S18.73.65 16 2.48a13.38 13.38 0 0 0-7 0C6.27.65 5.09 1 5.09 1A5.07 5.07 0 0 0 5 4.77a5.44 5.44 0 0 0-1.5 3.78c0 5.42 3.3 6.61 6.44 7A3.37 3.37 0 0 0 9 18.13V22"></path></svg>"""

[[extra.social_links]]
name = "Twitter"
url = "https://twitter.com/nullis"
icon = """<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M23 3a10.9 10.9 0 0 1-3.14 1.53 4.48 4.48 0 0 0-7.86 3v1A10.66 10.66 0 0 1 3 4s-4 9 5 13a11.64 11.64 0 0 1-7 2c9 5 20 0 20-11.5a4.5 4.5 0 0 0-.08-.83A7.72 7.72 0 0 0 23 3z"></path></svg>"""

[[extra.social_links]]
name = "LinkedIn"
url = "https://linkedin.com/in/nullis"
icon = """<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M16 8a6 6 0 0 1 6 6v7h-4v-7a2 2 0 0 0-2-2 2 2 0 0 0-2 2v7h-4v-7a6 6 0 0 1 6-6z"></path><rect x="2" y="9" width="4" height="12"></rect><circle cx="4" cy="4" r="2"></circle></svg>"""

[[extra.social_links]]
name = "Email"
url = "mailto:contact@nullis.xyz"
icon = """<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M4 4h16c1.1 0 2 .9 2 2v12c0 1.1-.9 2-2 2H4c-1.1 0-2-.9-2-2V6c0-1.1.9-2 2-2z"></path><polyline points="22,6 12,13 2,6"></polyline></svg>"""

# Contact Methods
[[extra.contact_methods]]
name = "Email"
type = "email"
value = "john.doe@example.com"
icon = """<svg viewBox="0 0 24 24" fill="none" stroke="currentColor"><path d="M3 8l7.89 5.26a2 2 0 002.22 0L21 8M5 19h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z"/></svg>"""
description = "Best for professional inquiries and collaborations"

[[extra.contact_methods]]
name = "GitHub"
type = "social"
value = "https://github.com/johndoe"
icon = """<svg viewBox="0 0 24 24" fill="none" stroke="currentColor"><path d="M9 19c-5 1.5-5-2.5-7-3m14 6v-3.87a3.37 3.37 0 00-.94-2.61c3.14-.35 6.44-1.54 6.44-7A5.44 5.44 0 0020 4.77 5.07 5.07 0 0019.91 1S18.73.65 16 2.48a13.38 13.38 0 00-7 0C6.27.65 5.09 1 5.09 1A5.07 5.07 0 005 4.77a5.44 5.44 0 00-1.5 3.78c0 5.42 3.3 6.61 6.44 7A3.37 3.37 0 009 18.13V22"/></svg>"""
description = "For code collaboration and open source projects"

# Footer Configuration
[extra.footer]
description = "Building robust, scalable solutions with a focus on security and efficiency"

[[extra.footer_links]]
title = "Quick Links"
links = [
    { label = "About", url = "/about" },
    { label = "Blog", url = "/blog" },
    { label = "Projects", url = "/projects" },
    { label = "Contact", url = "/contact" }
]

[[extra.footer_links]]
title = "Legal"
links = [
    { label = "Privacy Policy", url = "/privacy" },
    { label = "Terms of Service", url = "/terms" }
]

# Call-to-Action Configuration
[extra.cta]
title = "Let's Work Together"
description = "Interested in collaborating on a project? Get in touch to discuss how we can work together."
button_text = "Contact Me"
button_url = "/contact"
